@startuml
participant "seq-combined-api" as seq
participant "slow-api1" as api1
participant "slow-api2" as api2
seq -> api1: Requests slow api1
activate seq
note left
Total time consumed
end note
api1 --> seq: Slow api1 returns the result to seq-combined-api
seq -> api2: Requests slow api2
api2 --> seq: Slow api2 returns the result to seq-combined-api
deactivate seq
@enduml